# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BFF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BFF

 pod 'SwiftLint'
 pod 'Firebase/Analytics'
 pod 'FirebaseFirestoreSwift', '> 7.0-beta'
 pod 'IQKeyboardManagerSwift'
 pod 'Kingfisher'

end
